"""empty message

Revision ID: 35838aa0e1b6
Revises: 
Create Date: 2022-03-08 18:11:16.863527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35838aa0e1b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
